beta_start: 0.00085
beta_end: 0.012
beta_schedule: "scaled_linear"
clip_sample: false
steps_offset: 1

### Zero-SNR params
#rescale_betas_zero_snr: True
#timestep_spacing: "trailing"
timestep_spacing: "leading"