name: hf
channels:
  - defaults
dependencies:
  - pip=24.2
  - python=3.12.5
  - pip:
      - accelerate==1.2.1
      - deepspeed==0.16.2
      - diffusers==0.31.0
      - einops==0.8.0
      - gradio==5.9.1
      - gradio-client==1.5.2
      - huggingface-hub==0.29.3
      - kornia==0.7.4
      - kornia-rs==0.1.7
      - matplotlib==3.10.0
      - numpy==1.26.3
      - omegaconf==2.3.0
      - open-clip-torch==2.24.0
      - opencv-python==4.10.0.84
      - pillow==10.2.0
      - safetensors==0.4.5
      - timm==1.0.12
      - tokenizers==0.21.0
      - torch==2.5.1+cu121
      - torchdiffeq==0.2.5
      - torchsde==0.2.6
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==3.1.0
      - xformers==0.0.28.post3