name: hf
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip:
    - accelerate==0.24.1
    - deepspeed==0.12.2
    - einops==0.7.0
    - kornia==0.7.0
    - omegaconf==2.3.0
    - open-clip-torch==2.23.0
    - pytorch-lightning==2.1.1
    - safetensors==0.4.0
    - tokenizers==0.14.1
    - torch==2.1.2
    - torchdiffeq==0.2.3
    - torchsde==0.2.6
    - transformers==4.35.0
    - xformers==0.0.23.post1
    - gradio==4.13.0
    - basicsr==