model:
  base_learning_rate: 1.0e-6
  target: refnet.models.proj.InferenceWrapper
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: reference
    control_key: control
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: hybrid
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: true
    ucg_rate: 0.5
    rp: 0
    offset_noise_level: 0.05
    proj_heads: [ 64, 4 ]

    unet_config:
      target: refnet.modules.unet.InferenceProjUNet
      params:
        image_size: 32 # unused
        in_channels: 4
        c_channels: 3
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 1024
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: refnet.modules.encoders.OpenCLIP
      params:
        arch: ViT-H-14

dataloader:
  class: TripletLoader
  params:
    transform_list:
      flip: true
      rotate: false
      resize: true
      jitter: False
      rotate_range: 45
    refset_key: reference   # only use deformation training in ColorizeDiffusion v2
    load_size: 576
    crop_size: 512     # crop images to (crop_size, crop_size), randomly crop images when crop_size < load_size
    keep_ratio: false
    inverse_grayscale: true
  shuffle: true