model:
  base_learning_rate: 1.0e-6
  target: refnet.models.switch.InferenceWrapper
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    timesteps: 1000
    image_size: 64
    channels: 4
    scale_factor: 0.18215

    unet_config:
      target: refnet.modules.unet.DualCondUNet
      params:
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 1024
        use_checkpoint: false

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0

    cond_stage_config:
      target: refnet.modules.embedder.OpenCLIP
      params:
        arch: ViT-H-14

    control_encoder_config:
      target: refnet.modules.encoder.MultiEncoder
      params:
        in_ch: 3
        model_channels: 320
        ch_mults: [1, 2, 4, 4]

    lora_config:
      fr: 4
      br: 0.5

    transformer_config:
      target: refnet.modules.proj.ClusterTransformer
      params:
        dim: 1024
        layers: 6
        token_length: 256

    thresh_embedder_config:
      target: refnet.modules.embedder.ScalarEmbedder
      params:
        embed_dim: 256
        out_dim: 1024

    proj_config:
      target: torch.nn.Identity
