gmodel:
  base_learning_rate: 1.0e-6
  target: refnet.models.trainer.trainer.ColorizerTrainer
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    timesteps: 1000
    image_size: 64
    channels: 4
    control_key: control
    cond_stage_key: reference
    scale_factor: 0.18215
    parameterization: eps

    unet_config:
      target: refnet.modules.unet_old.DualCondUNet
      params:
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 1024
        use_checkpoint: false

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0

    cond_stage_config:
      target: refnet.modules.embedder.OpenCLIP
      params:
        arch: ViT-H-14

    control_encoder_config:
      target: refnet.modules.encoder.MultiEncoder
      params:
        in_ch: 3
        model_channels: 320
        ch_mults: [1, 2, 4, 4]

    proj_config:
      target: torch.nn.Identity


dataloader:
  class: TripletLoader
  dataset_params:
    condition_key: color
  transforms:
    transform_list:
      flip: true
      rotate: false
      resize: true
      jitter: false
      rotate_range: 45
    load_size: 512
    crop_size: 512       # crop images to (crop_size, crop_size), randomly crop images when crop_size < load_size
    keep_ratio: false
    inverse_grayscale: true
  shuffle: true