model:
  base_learning_rate: 1.0e-6
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: color
    image_size: 64
    channels: 4
    monitor: val/loss_simple_ema
    cond_stage_key: colorize
    conditioning_key: colorize
    scale_factor: 0.18215

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.DualCondUnetModel
      params:
        in_channels: 4
        c_channels: 1
        out_channels: 4
        model_channels: 320
        attention_resolutions: [4, 2, 1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_head_channels: 64
        use_checkpoint: true
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 1024

    first_stage_config:
      target: models.autoencoder.VAE
      params:
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 512
          in_ch: 3
          out_ch: 3
          num_res_blocks: 2
          ch: 128
          ch_mult: [1, 2, 4, 4]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_trainable: true
    cond_stage_config:
      target: models.wrapper.ConditionWrapper
      params:
        drop_rate: 0.5
        clip_config:
          scale_factor: 1.0
          type: tokens

dataloader:
  class: DraftLoader    # ['ImageLoader', 'DraftLoader']
  params:
    transform_list:
      flip: true
      rotate: false
      resize: true
      jitter: False
      rotate_range: 45
    load_size: 576
    crop_size: 512     # crop images to (crop_size, crop_size), randomly crop images when crop_size < load_size
    use_tokens: true
    keep_ratio: true
  shuffle: true