model:
  base_learning_rate: 1.0e-6
  target: models.cldm.ControlLDM
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: color
    cond_stage_key: colorize
    image_size: 64
    channels: 4
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    conditioning_key: crossattn

    control_stage_config:
      target: models.cldm.ControlNet
      params:
        use_checkpoint: True
        in_channels: 4
        hint_channels: 1
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
#        use_tokens: true

    unet_config:
      target: models.cldm.ControlledUnetModel
      params:
        use_checkpoint: True
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        use_tokens: true
        legacy: False

    first_stage_config:
      target: models.autoencoder.VAE
      params:
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 512
          in_ch: 3
          out_ch: 3
          num_res_blocks: 2
          ch: 128
          ch_mult: [1, 2, 4, 4]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_trainable: false
    cond_stage_config:
      target: ldm.modules.encoders.modules.OpenCLIPEncoder
      params:
        scale_factor: 1.0
        type: tokens

dataloader:
  class: DraftLoader    # ['ImageLoader', 'ReferLoader', 'DraftLoader']
  params:
    transform_list:
      flip: true
      rotate: false
      resize: true
      jitter: False
      rotate_range: 45
    load_size: 576
    crop_size: 512      # crop images to (crop_size, crop_size), randomly crop images when crop_size < load_size
    use_tokens: true
    keep_ratio: true
  shuffle: true