model:
  base_learning_rate: 1.0e-6
  target: refnet.models.trainer.colorizer.ColorizerTrainer
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: reference
    control_key: control
    image_size: 96
    channels: 4
    scale_factor: 0.18215
    use_ema: false
    ucg_rate: 0.5
    offset_noise_level: 0.05

    unet_config:
      target: refnet.modules.unet.DualCondUNet
      params:
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 1024
        use_checkpoint: True

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0

    cond_stage_config:
      target: refnet.modules.embedder.FrozenOpenCLIPImageEmbedder
      params:
        arch: ViT-H-14

    control_encoder_config:
      target: refnet.modules.encoder.MultiEncoder
      params:
        in_ch: 3
        model_channels: 320
        ch_mults: [1, 2, 4, 4]

    proj_config:
      target: torch.nn.Identity

dataloader:
  class: ZipTripletLoader
  dataset_params:
    json_key: image_list
    condition_key: color
    minimum_image_size: 768
    score_threshold: 5.5
  transforms:
    transform_list:
      flip: false
      rotate: false
      resize: true
      jitter: false
      rotate_range: 45
    load_size: 961
    crop_size:
      - [ 768, 768 ]
      - [ 768, 768 ]
      - [ 768, 768 ]
      - [ 768, 768 ]
      - [ 704, 832 ]
      - [ 832, 704 ]
      - [ 896, 640 ]
      - [ 640, 896 ]
      - [ 960, 576 ]
      - [ 576, 960 ]
    center_crop_max: 150
    keep_ratio: false
    inverse_grayscale: true
  shuffle: true