model:
  base_learning_rate: 1.0e-6
  target: refnet.models.trainer.v2.Trainer
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    timesteps: 1000
    image_size: 96
    channels: 4
    scale_factor: 0.18215
    parameterization: v
    ucg_rate: 0.5
    use_ema: false
    offset_noise_level: 0.05
    p_white_bg: 0.05
    training_stage: 0

    bg_encoder_config:
      target: refnet.modules.unet.UNetEncoder
      params:
        in_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 1024
        use_checkpoint: true
        adm_in_channels: 512
        num_classes: sequential

    style_encoder_config:
      target: refnet.modules.unet.UNetEncoder
      params:
        in_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 1024
        use_checkpoint: true
        adm_in_channels: 512
        num_classes: sequential
        style_modulation: true

    unet_config:
      target: refnet.modules.unet.DualCondUNet
      params:
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 1024
        use_checkpoint: true
        warp_module: true
        style_modulation: true

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0

    cond_stage_config:
      target: refnet.modules.embedder.FrozenOpenCLIPImageEmbedder
      params:
        arch: ViT-H-14

    control_encoder_config:
      target: refnet.modules.encoder.MultiEncoder
      params:
        in_ch: 3
        model_channels: 320
        ch_mults: [1, 2, 4, 4]

    ratio_embedder_config:
      target: refnet.modules.embedder.TimestepEmbedding
      params:
        embed_dim: 256

    proj_config:
      target: torch.nn.Identity
      
    lora_config:
      fr: 4
      br: 4

dataloader:
  class: QuartLoader
  dataset_params:
    condition_key: color
    minimum_image_size: 1024
  transforms:
    transform_list:
      flip: false
      rotate: false
      resize: true
      jitter: false
      rotate_range: 45
    load_size: 1024
    crop_size:
      - [ 768, 768 ]
      - [ 768, 768 ]
      - [ 768, 768 ]
      - [ 768, 768 ]
      - [ 704, 832 ]
      - [ 832, 704 ]
      - [ 896, 640 ]
      - [ 640, 896 ]
      - [ 960, 576 ]
      - [ 576, 960 ]
    keep_ratio: false
    inverse_grayscale: true
    center_crop_max: 200
  shuffle: true